language: node_js
node_js : 
  - "9.8.0"

install:
    - npm install -g gulp
    - npm --production=false install

script: gulp build

before_deploy:
    - rm .gitignore
    - echo -e "node_modules/" > .gitignore

deploy:
  email: $GH_MAIL
  name: $GH_NAME
  provider: pages
  skip_cleanup: true
  github_token: $PAT
  on:
    branch: master

branches:
    only:
        - master
        - develop